<?php

/***************************************************************************
      This file was automatically generated by Admin FAQ Editor
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/

//
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
//
// The FAQ items will appear on the FAQ page in the same order they are listed in this file
//

$faq[] = array("--", "Prílohy");
$faq[] = array("Ako pridám prílohu?", "Prílohy môžete pridať počas pridávania nového príspevku. Mali by ste vidieť pod hlavným panelom príspevku formulár <i>Pridať prílohu</i>. Keď kliknete na tlačidlo <i>Prehliadať...</i>, otvorí sa vo vašom počítači štandardné dialógové okno pre otvorenie súboru. Nájdite súbor, ktorý chcete priložiť, kliknite naňho a následne na OK, Otvoriť alebo dvakrát naňho kliknite (závisí od vašich preferencií a/alebo správneho postupu pre váš počítač). Pokiaľ sa rozhodnete pridať komentár do poľa <i>Komentár k súboru</i>, tento komentár sa použije ako odkaz k priloženému súboru. Pokiaľ komentár nepridáte, ako odkaz k prílohe sa použije samotný názov súboru. Pokiaľ to správca fóra povolil, budete môcť nahrať viacero príloh a to úplne rovnakým postupom popísaným vyššie. A to až kým dosiahnete najvyšší povolený počet príloh pre jednotlivé príspevky.<br/><br/>Správca fóra nastavuje horný limit pre veľkosť súboru, definuje prípony súbory a ďalšie veci týkajúce sa príloh v tomto fóre. Buďte si vedomí toho, že je vašou zodpovednosťou, aby prílohy spĺňali politiku prijateľnosti použitia. Inak môžu byť bez upozornenia vymazané.<br/><br/>Majte na pamäti, že vlastník fóra, správca webovej stránky, správca a ani moderátori nemôžu a ani nechcú prevziať zodpovednosť za akúkoľvek stratu dát.");
$faq[] = array("Ako pridám prílohu už po pridaní príspevku?", "Aby ste pridali prílohu potom, ako bol už príspevok pridaný, budete musieť upraviť váš príspevok a riadiť sa popisom vyššie. Novú prílohu pridáte kliknutím na <i>Odoslať</i> v upravovanom príspevku.");
$faq[] = array("Ako vymažem prílohu?", "Aby ste vymazali prílohu, budete potrebovať upraviť váš príspevok a kliknúť v paneli <i>Pridané prílohy</i> na tlačidlo <i>Vymazať prílohu</i> vedľa prílohy, ktorú chcete vymazať. Príloha sa vymaže, keď kliknete na tlačidlo <i>Odoslať</i> v upravovanom príspevku.");
$faq[] = array("Ako aktualizujem komentár k súboru?", "Aby ste mohli aktualizovať komentár k súboru, budete musieť váš príspevok upraviť, upraviť text v poli <i>Komentár k súboru</i> a kliknúť na tlačidlo <i>Aktualizovať komentár</i> vedľa komentára, ktorý chcete aktualizovať v paneli <i>Pridané prílohy</i>. Komentár bude aktualizovaný, keď kliknete na tlačidlo <i>Odoslať</i> v upravovanom príspevku.");
$faq[] = array("Prečo nie je moja príloha viditeľná v príspevku?", "S najväčšou pravdepodobnosťou táto prípona už nie je viac v tomto fóre povolená, alebo ju moderátor alebo správca vymazal, pretože bola v konflikte s politikou prijateľnosti použitia.");
$faq[] = array("Prečo nemôžem pridať prílohy?", "Na niektorých fórach môže byť pridávanie príloh obmedzené len pre určitých používateľov alebo skupiny. Aby ste mohli pridať prílohy, môžete potrebovať zvláštne oprávnenie. Takýto prístup môže udeliť iba moderátor a správca fóra. Mali by ste ich kontaktovať.");
$faq[] = array("Mám potrebné povolenia. Prečo nemôžem pridať prílohy?", "Správca fóra nastavuje horný limit pre veľkosť súboru, prípony súborov a iné veci týkajúce sa príloh vo fóre. Moderátor alebo správca vám mohli povolenia pozmeniť alebo mohli v konkrétnom fóre prílohy zakázať. Keď sa pokúsite pridať prílohu, mali by ste vidieť vysvetlenie v chybovej správe. Pokiaľ nie, mali by ste zvážiť kontaktovanie moderátora alebo správcu.");
$faq[] = array("Prečo nemôžem mazať prílohy?", "Na niektorých fórach môže byť mazanie príloh obmedzené len pre určitých používateľov alebo skupiny. Aby ste mohli vymazať prílohu, môžete potrebovať zvláštne oprávnenie. Takýto prístup môže udeliť iba moderátor a správca fóra. Mali by ste ich kontaktovať.");
$faq[] = array("Prečo si nemôžem zobraziť/stiahnuť prílohy?", "Na niektorých fórach môže byť zobrazenie/sťahovanie obmedzené len pre určitých používateľov alebo skupiny. Aby ste si mohli zobraziť/stiahnuť prílohu, môžete potrebovať zvláštne oprávnenie. Takýto prístup môže udeliť iba moderátor a správca fóra. Mali by ste ich kontaktovať.");
$faq[] = array("Koho mám kontaktovať ohľadom ilegálnych alebo možno ilegálnych príloh?", "Mali by ste kontaktovať správcu tohto fóra. 
<br />Pokiaľ neviete zistiť, kto ním je, mali by ste najprv kontaktovať jedného z moderátorov fóra a spýtať sa, na koho sa máte obrátiť. 
<br />E-mailovú adresa admin@... [táto doména] vždy spracuje správca stránky.");



?>